services:
  web:
    build:
      context: ./web
    ports:
      - "5000:5000"
      
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - web
      - index  # Adicionar dependência ao container de índice

  index:
    build:
      context: ./index
    ports:
      - "80:80"

volumes:
  db_data: